<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- 
        Asyns-await sinh ra ở phiên bải ES7
        sinh ra giải quyết vấn đề xử lí bất đồng bộ
        giúp cho vc viết code bằng promise trỏe nên gọn gàng hơn
        async đc đặt trc 1 function thì sẽ biến function đấy thành 1 promise
        nếu trong promise mà muốn bắt lỗi thì dùng .catch-reject()
        trong anync await làm sao để bắt lỗi đc
        try-catch
        await chỉ đợi những tác vụ promise thôi
     -->
     <script>
        async function asyncAwait(params) {
        await new Promise((resolve,reject) => {
                setTimeout(() => {
                    console.log("1111");
                    // Khi tác vụ promise đó có resolve hoặc reject thì
                    // Tác vụ đấy mới được xem là hoàn thành , còn ko là pending
                    resolve()
                },2000)
            })
            console.log("3333");
        }
        console.log(asyncAwait());
        // function lấy dữ liệu 
        async function getData() {
            fetch("https://jsonplaceholder.typicode.com/users")
            .then(user => user.json())
            .then(data => {
                console.log("Dữ liệu khi lấy về ", data);
            })
        }
        // getData();
        // try {
        //     // Viết logic thực thi
        //     async function getData() {
        //         await fetch("https://jsonplaceholder.typicode.com/users")
        //     }
        //     getData();
        // } catch (error) {
        //     console.log("111111",error);
        // }
        try {
            console.log(a);
        } catch (error) {
            console.log(error);
        }
        console.log(11111);
     </script>
</body>
</html>